---
name: Link Milestone
on:
  workflow_run:
    workflows: ['Link Milestone Upload PR Number']
    types:
      - completed

jobs:
  link-milestone:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: true
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: pr
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.7'
      - run: |
          export PR_NUMBER=$(cat ./pr/nr)
          go install github.com/stephybun/link-milestone@latest
          link-milestone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
